[package]
name = "thing"
version = "0.1.0"
license = "GPL3"
kind = "Binary"
backend = "C"
binaries = ["validator"]

[toolchain]
version = "2.2.4"

[dependencies]
jsony = ">= 1.1.5"
url = ">= 0.0.0"
shakar = ">= 0.1.3"
results = ">= 0.5.1"
